version: '3.8'

services:
  app:
    image: marce35/kiii-final-project:latest
    container_name: kiii_app_container
    build:
      context: ./kol2022-g2-updated
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/KIII-project-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:latest
    container_name: kiii_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: KIII-project-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 3
