apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kiii-namespace
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM= # base64 encoded value of "postgres"
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=     # base64 encoded value of "admin"