apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kiii-namespace
  name: db-pv
  labels:
    type: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data