name: Build and Push Docker Image 

on:
  push:
    branches:
      - master 

jobs:
  build-and-push-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kiii-final-project:latest kol2022-g2-updated
    
    # Step 5: Push the Docker image to DockerHub
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kiii-final-project:latest

    # Step 6: Cleanup unused Docker resources (optional)
    - name: Cleanup Docker
      run: |
        docker system prune -f
